### ISSUE TITLE
[BUG] fzf issue at start

### ISSUE THREAD

**Issue by bachig26** [mov-cli/porn-cli#2]
**Describe the bug**
1. when I try to use up arrow to navigate the providers list, the app gets automatically initiates the pornhub provider instead of moving up for navigation.
2. also the command ctrl-c to close the cli makes it open the default provider.

**Expected behavior**
up arrow scrolls up the providers list instead of opening the default provider.

**Screenshots**
nil

**Error**
````
None
[!] Warning: This Provider contains Porn

Continue? [y/n]: [A
````
the up arrow opens the default provider and calls `[A`.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version: 10

**Additional context**
nil

**Possible cause**
nil

**Possible solution**
nil

**Version**
1.0.0

**Comment by R3tr0Ananas** [comment]
i can't repro that error.
